import{a as d,S as y,i as g}from"./assets/vendor-550cebad.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();let n=1,c;async function L(t){const o="43068097-aa3ed59823608d0655ab40c7d",s="https://pixabay.com/api/",a=new URLSearchParams({key:o,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:15});try{const e=await d.get(s,{params:a});if(e.status!==200)throw new Error("Error");const r=e.data;return r.totalHits===0?null:r}catch(e){return e}}async function v(t){let o;t.target===document.querySelector(".more-btn")?(o=c,n+=1):(c=t.target.elements.search.value.trim(),o=c,n=1);const s="43068097-aa3ed59823608d0655ab40c7d",a="https://pixabay.com/api/",e=new URLSearchParams({key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:15});try{const r=await d.get(a,{params:e});if(r.status!==200)throw new Error("Error");const i=r.data;return i.totalHits===0?null:i}catch(r){return r}}function S(t,o){if(!Array.isArray(t)){console.error(Error);return}const s=t.map(({webformatURL:a,largeImageURL:e,tags:r,likes:i,views:m,comments:f,downloads:h})=>`<li class="gallery-item">
        <a href="${e}">
          <img
            src="${a}"
            data-source="${e}"
            alt="${r}"
          />
          <ul class="gallery-description">
            <li class="gallery-desc-item"><div class="desc-info"><h3>Likes</h3><p>${i}</p></div></li>
            <li class="gallery-desc-item"><div class="desc-info"><h3>Views</h3><p>${m}</p></div></li>
            <li class="gallery-desc-item"><div class="desc-info"><h3>Comments</h3><p>${f}</p></div></li>
            <li class="gallery-desc-item"><div class="desc-info"><h3>Downloads</h3><p>${h}</p></div></li>
          </ul>
        </a>
      </li>`).join("");o?(o.innerHTML=s,new y(".gallery-item a",{captionsData:"alt",captionDelay:250})):console.error(Error)}const q=document.querySelector("#search-form"),l=document.querySelector(".gallery"),u=document.querySelector(".loader"),p=document.querySelector(".more-btn");q.addEventListener("submit",t=>{t.preventDefault(),l.innerHTML="";const o=t.target.querySelector("#search-input").value.trim();o&&(u.classList.add("loading"),L(o).then(s=>{s===null?g.error({position:"topRight",title:"❌",icon:"",message:"Sorry, there are no images matching your search query. Please try again!"}):(S(s.hits,l),w(s.hits))}).catch(s=>{console.error(s)}).finally(()=>{u.classList.remove("loading")})),t.target.reset()});p.addEventListener("click",t=>{v(t)});function w(t){p.classList.toggle("is-hidden",t.length===0)}
//# sourceMappingURL=commonHelpers.js.map
